# Address on which to listen for dns registration requests
dns_listen_addr = "[::]:53"

# Base domain authoritive to nameserver
domain = "r.refraction.network"

# Path to Conjure private key file
dns_private_key_path = "/var/lib/conjure/privkey"

# Log level, one of the following: panic, fatal, error, warn, info, debug, trace
log_level = "info"

# Interval in seconds between every metrics log
log_metrics_interval = 5

# The port on which to host the API
api_port = 8080

# The port on which to bind the ZMQ port
zmq_port = 5591
zmq_bind_addr = "*"

# The path on disk to the private key used for the ZMQ socket
zmq_privkey_path = "/var/lib/conjure/privkey"

# The type of authentication to use on the ZMQ socket.
# Can be set to "NULL" which allows all connections, or "CURVE"
# which only allows clients presenting public keys listed in
# station_pubkeys below.
zmq_auth_type = "CURVE"

# Whether ZMQ should emit verbose logs pertaining to auth (successful connections, failed connections, etc.)
zmq_auth_verbose = true

# The public keys used to authorize ZMQ connections in the CURVE type.
# These should be the Z85-encoded versions of the 32-byte public keys,
# giving 40-character strings.
station_pubkeys = [
	"",
]

# This field specifies the generation number that the Bidirectional API
# registrar will use when selecting phantoms.
bidirectional_api_generation = 957

# Path on disk to the latest ClientConfig file that the station should use
clientconf_path = "/var/lib/conjure/ClientConf"

# Whether to apply the below subnet overrides to clients bidirectional api registrations
enforce_subnet_overrides = true

# Percentage of bidirectional api registrations to override per transport
prcnt_min_regs_to_override = 100
prcnt_prefix_regs_to_override = 100

# Subnets to use when overriding clients bidirectional api registrations
[[override_subnet]]
cidr = "X.X.X.X/32"
weight = 10.7
port = 443
transport = "Min_Transport"

[[override_subnet]]
cidr = "X.X.X.X/24"
weight = 10
port = 80
transport = "Prefix_Transport"
prefix_id = 1

# Subnets to refrain from overriding when clients bidirectional api registrations pick a v4 phantom inside them
[[excluded_subnet_from_overrides]]
cidr = "X.X.X.X/25"
# For future features that can exclude subnets according to weight, port, or transport
weight = 28.7
port = 80
transport = "Min_Transport"
