# Address on which to listen for dns registration requests
addr = "[::]:53"

# URLs for unidirectional and bidirectional registration API
api_url = "http://localhost:8080/register"
bdapi_url = "http://localhost:8080/register-bidirectional"

# Base domain authoritive to nameserver
domain = "r.refraction.network"

# Path to Conjure private key file
private_key_path = "/opt/conjure/sysconfig/privkey"

# Log level, one of the following: panic, fatal, error, warn, info, debug, trace
log_level = "trace"
